# -*- coding: utf-8 -*-
"""Torrent Google Drive By Me.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIE0xKRAnCvIMy7XttLPKSMezZUj1LpA

**Torrent To Google Drive/ShareDrive BY
RH Rafiz**
"""

# প্রয়োজনীয় লাইব্রেরি ইনস্টল করা
!pip install -q libtorrent

# মডিউল ইম্পোর্ট করা
import libtorrent as lt
import time
import os
import shutil
from google.colab import drive
from google.colab import output

print("লাইব্রেরি ইনস্টল এবং ইম্পোর্ট সম্পন্ন হয়েছে।")
# গুগল ড্রাইভ মাউন্ট করা হচ্ছে
# এটি করার মাধ্যমে Colab আপনার গুগল ড্রাইভের ফাইল অ্যাক্সেস করার অনুমতি পাবে
drive.mount('/content/drive')

# টরেন্ট সেশন শুরু করার জন্য সেটিংস
ses = lt.session()
ses.listen_on(6881, 6891)

# লোকাল ডাউনলোডের জন্য একটি ফোল্ডার তৈরি করা (Colab environment-এ)
download_path_local = "/content/drive/MyDrive/Torrents"
if not os.path.exists(download_path_local):
    os.makedirs(download_path_local)

# ব্যবহারকারীর কাছ থেকে ইনপুট নেওয়া
magnet_link = input("আপনার ম্যাগনেট লিংকটি এখানে পেস্ট করুন: ")
gdrive_folder_path = "/content/drive/MyDrive/MyTorrents"

# গুগল ড্রাইভের ফোল্ডারটি না থাকলে তৈরি করা
if not os.path.exists(gdrive_folder_path):
    os.makedirs(gdrive_folder_path)
    print(f"'{gdrive_folder_path}' ফোল্ডারটি তৈরি করা হয়েছে।")

# টরেন্ট যোগ করা
params = {'save_path': download_path_local}
handle = lt.add_magnet_uri(ses, magnet_link, params)

print("\nটরেন্টের মেটাডেটা ডাউনলোড করা হচ্ছে...")
while not handle.has_metadata():
    time.sleep(1)

tor_info = handle.get_torrent_info()
file_name = tor_info.name()
print(f"ডাউনলোড শুরু হচ্ছে: {file_name}")

# রিয়েল-টাইম স্ট্যাটাস দেখানোর লুপ
while handle.status().state not in [lt.torrent_status.seeding, lt.torrent_status.finished]:
    s = handle.status()
    progress = s.progress * 100
    download_speed = s.download_rate / 1024 / 1024  # MB/s
    peers = s.num_peers

    # আউটপুট ক্লিয়ার করে নতুন স্ট্যাটাস দেখানো
    output.clear()

    print(f"ফাইলের নাম: {file_name}")
    print(f"অগ্রগতি: {progress:.2f}%")
    # একটি সাধারণ টেক্সট-ভিত্তিক প্রোগ্রেস বার
    progress_bar = '█' * int(progress / 2) + '-' * (50 - int(progress / 2))
    print(f"[{progress_bar}]")
    print(f"ডাউনলোডের গতি: {download_speed:.2f} MB/s")
    print(f"পিয়ারস (Peers): {peers}")
    print(f"স্ট্যাটাস: {s.state}")

    time.sleep(5)

output.clear()
print(f"✅ ডাউনলোড সম্পন্ন: {file_name}")

# ডাউনলোড হওয়া ফাইল গুগল ড্রাইভে মুভ করা
source_file = os.path.join(download_path_local, file_name)
destination_file = os.path.join(gdrive_folder_path, file_name)

print(f"\nফাইলটি গুগল ড্রাইভে মুভ করা হচ্ছে...")
shutil.move(source_file, destination_file)
print(f"🚀 সফলভাবে '{file_name}' ফাইলটি আপনার গুগল ড্রাইভে সেভ করা হয়েছে!")
print(f"ড্রাইভের পাথ: {destination_file}")