# -*- coding: utf-8 -*-
"""torrent2drive.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/cinepagla24/580299bd467e0d1ffab748bdece730d2/torrent2drive.ipynb
"""

# ================================================================
# 🚀 Google Colab Auto Installer (Optimized & Fixed Version)
# By RJ Sheesh | Fixed by ChatGPT
# ================================================================

import os
import subprocess
from google.colab import drive
from IPython.display import clear_output

# ---------- Configuration ----------
TORRENTS_DIR = "/content/drive/MyDrive/Torrents"

# ---------- Utility Functions ----------
def log(msg):
    print(f"\033[92m{msg}\033[0m")  # Green

def warn(msg):
    print(f"\033[93m{msg}\033[0m")  # Yellow

def run_command(command, description):
    log(f"🔄 {description}...")
    result = subprocess.run(command, shell=True, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"\033[91mError running command: {command}\033[0m")
        print(f"Stderr: {result.stderr}")
        raise RuntimeError(f"Failed to execute: {description}")
    clear_output(wait=True)
    log(f"✅ {description} complete!")

# ---------- Main Execution ----------
try:
    # Step 1: Mount Google Drive
    log("🔄 Step 1: Mounting Google Drive...")
    drive.mount('/content/drive')
    clear_output(wait=True)
    log("✅ Google Drive Mounted Successfully!")

    # Step 2: Install Python 3.10
    run_command(
        "apt-get update -y && "
        "apt-get install -y software-properties-common && "
        "add-apt-repository -y ppa:deadsnakes/ppa && "
        "apt-get update -y && "
        "apt-get install -y python3.10 python3.10-dev python3.10-distutils libpython3.10-dev curl",
        "Installing Python 3.10 and dependencies"
    )

    # Step 3: Create Torrents Folder
    if not os.path.exists(TORRENTS_DIR):
        log(f"📁 Creating folder: {TORRENTS_DIR}")
        os.makedirs(TORRENTS_DIR)
    else:
        warn(f"✅ Folder already exists: {TORRENTS_DIR}")

    # Step 4: Install pip for Python 3.10
    run_command(
        "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && "
        "python3.10 get-pip.py",
        "Installing pip for Python 3.10"
    )

    # Step 5: Install required Python packages
    run_command(
        "python3.10 -m pip install --upgrade pip && "
        "python3.10 -m pip install libtorrent IPython tqdm colorama",
        "Installing required Python packages"
    )

    # Step 6: Install aria2 (fixed)
    run_command(
        "apt-get install -y aria2",
        "Installing aria2"
    )

    # Final Step
    os.chdir(TORRENTS_DIR)
    log("🎉 All tasks completed successfully!")
    print(f"\nPython 3.10, pip, aria2 and all packages installed.")
    print(f"Current directory: {os.getcwd()}")

except Exception as e:
    print(f"\033[91m❌ An error occurred: {e}\033[0m")

# Now Try Version v1 Run
!python3.10 /content/drive/MyDrive/Torrents/tor2gd_v1.py

# Now Try Version v2 Run
!python3.10 /content/drive/MyDrive/Torrents/tor2gd_v2.py

# Now Try Version v3 Run
!python3 /content/drive/MyDrive/Torrents/tor2gd_v3.py